version: '3'

services:
  minecraft:
    container_name: minecraft
    stdin_open: true
    tty: true
    build:
      context: './'
      dockerfile: 'Dockerfile'
    environment:
      XMS: "${XMS}"
      XMX: "${XMX}"
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - "${WORLDS_ROOT}:/minecraft/server/worlds"