version: '3'

services:
  minecraft:
    container_name: minecraft
    stdin_open: true
    tty: true
    build:
      context: './'
      dockerfile: 'Dockerfile'
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "8123:8123"
    volumes:
      - "${WORLD_ROOT}:/minecraft/server/world"
      - "${CONFIG_ROOT}:/minecraft/server/config"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1454